
### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

### 
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 2",
    "email": "partner2@user.com",
    "password": "secret",
    "company_name": "Company Name 2"
}

###  
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "a customer",
    "email": "emailtest@gmail.com",
    "password": "secret",
    "address": "partner1@user.com",
    "phone": "1212131231"
}

### 
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "a name",
    "description": "a some description",
    "date": "2025-01-01T00:00:00",
    "location": ""
}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/1